import type { Metadata } from "next";
import { Darker_Grotesque } from "next/font/google";
import "./globals.css"; // Ensure Tailwind is imported
import Header from "./components/Header";
import Navigation from "./components/Navbar";
import Footer from "./components/Footer";

const darkerGrotesque = Darker_Grotesque({
  subsets: ["latin"], // Supports Latin characters
  weight: ["300", "400", "500", "600", "700", "800", "900"], // Select font weights
  variable: "--font-darker-grotesque", // Define a CSS variable for Tailwind
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const footerSections = [
  {
    title: "concierge",
    links: ["contact", "size & fit", "track an order", "shipping & delivery", "account", "FAQ"]
  },
  {
    title: "company",
    links: ["who we are", "sustainability"]
  },
  {
    title: "legal",
    links: ["return & cancellation policy", "accessibility policy", "privacy policy", "terms of service", "do not sell or share my personal data​"]
  },
  {
    title: "social",
    links: ["instagram", "spotify", "pinterest"]
  }
];

const paymentMethods = [
  "/payment/visa.svg",
  "/payment/mastercard.svg",
  "/payment/paypal.svg",
  "/payment/klarna.svg",
  "/payment/applepay.svg",
  "/payment/afterpay.svg",
  "/payment/shoppay.svg",
  "/payment/googlepay.svg",
  "/payment/amex.svg"
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${darkerGrotesque.variable} antialiased`}
      >
      <Header/>
      <Navigation/>
        {children}
      <Footer sections={footerSections} paymentMethods={paymentMethods} />
      </body>
    </html>
  );
}
