import type { Metadata } from "next";
import { Darker_Grotesque } from "next/font/google";
import "./globals.css"; // Ensure Tailwind is imported

const darkerGrotesque = Darker_Grotesque({
  subsets: ["latin"], // Supports Latin characters
  weight: ["300", "400", "500", "600", "700", "800", "900"], // Select font weights
  variable: "--font-darker-grotesque", // Define a CSS variable for Tailwind
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${darkerGrotesque.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
